version: '3.8'

services:
  vue-app:
    image: node:18  # 使用 Node.js 官方镜像
    working_dir: /app  # 设置工作目录
    volumes:
      - .:/app  # 将当前目录挂载到容器的 /app 目录
    command: >
      sh -c "npm install && npm run build && npm install -g serve && serve -s dist"  # 安装依赖、构建项目并启动服务
    ports:
      - "8080:3000"  # 将容器的 3000 端口映射到主机的 8080 端口
    environment:
      - NODE_ENV=production  # 设置环境变量
    restart: always  # 容器崩溃后自动重启